/** Curated automotive terms for R2 (case-insensitive word-boundary match). */
export const CAR_KEYWORDS = [
  // Vehicle nouns
  "auto",
  "automobile",
  "car",
  "minivan",
  "sedan",
  "suv",
  "truck",
  "van",
  "vehicle",
  "vin",

  // Major systems / parts
  "abs",
  "accelerator",
  "ac",
  "airbag",
  "air filter",
  "alternator",
  "antifreeze",
  "axle",
  "battery",
  "belt",
  "brake",
  "brakes",
  "braking",
  "bumper",
  "cabin",
  "caliper",
  "camshaft",
  "catalytic",
  "catalytic converter",
  "clutch",
  "coolant",
  "crankshaft",
  "cv joint",
  "dashboard",
  "defroster",
  "diesel",
  "differential",
  "drivetrain",
  "engine",
  "exhaust",
  "fender",
  "filter",
  "fluid",
  "fuel",
  "fuel pump",
  "fuse",
  "gas",
  "gasoline",
  "gasket",
  "gear",
  "gearbox",
  "headlight",
  "heater",
  "hood",
  "horn",
  "hose",
  "ignition",
  "injector",
  "muffler",
  "odometer",
  "oil",
  "oil change",
  "oil leak",
  "pedal",
  "piston",
  "power steering",
  "radiator",
  "rotor",
  "rpm",
  "serpentine",
  "shock",
  "shocks",
  "spark",
  "spark plug",
  "spark plugs",
  "speedometer",
  "starter",
  "steering",
  "strut",
  "suspension",
  "tailpipe",
  "taillight",
  "thermostat",
  "throttle",
  "tire",
  "tires",
  "transmission",
  "trunk",
  "turbo",
  "wheel",
  "wheels",
  "windshield",
  "wiper",
  "wipers",

  // Symptoms / driver language (no "car" required)
  "check engine",
  "check engine light",
  "engine light",
  "flat tire",
  "grinding",
  "knocking",
  "leak",
  "leaking",
  "misfire",
  "misfiring",
  "overheat",
  "overheating",
  "pulling",
  "rattling",
  "squealing",
  "stalling",
  "vibration",
  "warning light",
  "won't start",
  "wont start",
  "will not start",
] as const;

/** Safety-related terms for R3 — sets safety_flag without blocking. */
export const SAFETY_KEYWORDS = [
  "airbag",
  "brake failure",
  "brakes failed",
  "brakes not working",
  "can't stop",
  "cannot stop",
  "collision",
  "crash",
  "explosion",
  "fire",
  "flames",
  "fuel leak",
  "gas leak",
  "no brakes",
  "on fire",
  "overheating",
  "pull over",
  "seized",
  "smoke",
  "sparks",
  "stalling",
  "steering failure",
  "steering locked",
  "steering wheel",
  "stuck accelerator",
  "uncontrollable",
  "won't stop",
] as const;
