/** Curated automotive terms for R2 (case-insensitive word-boundary match). */
export const CAR_KEYWORDS = [
  "accelerator",
  "ac",
  "airbag",
  "alternator",
  "antifreeze",
  "auto",
  "automobile",
  "axle",
  "battery",
  "belt",
  "brake",
  "brakes",
  "bumper",
  "cabin",
  "camshaft",
  "car",
  "catalytic",
  "clutch",
  "coolant",
  "crankshaft",
  "dashboard",
  "defroster",
  "diesel",
  "differential",
  "door",
  "drive",
  "drivetrain",
  "engine",
  "exhaust",
  "fender",
  "filter",
  "fluid",
  "fuel",
  "gas",
  "gasoline",
  "gear",
  "gearbox",
  "gasket",
  "headlight",
  "heater",
  "hood",
  "horn",
  "hose",
  "ignition",
  "injector",
  "leak",
  "muffler",
  "odometer",
  "oil",
  "overheat",
  "pedal",
  "piston",
  "radiator",
  "rpm",
  "shift",
  "shock",
  "spark",
  "speedometer",
  "starter",
  "steering",
  "strut",
  "suspension",
  "tailpipe",
  "taillight",
  "thermostat",
  "throttle",
  "tire",
  "tires",
  "transmission",
  "trunk",
  "turbo",
  "vehicle",
  "vin",
  "wheel",
  "wheels",
  "windshield",
  "wiper",
] as const;

/** Safety-related terms for R3 — sets safety_flag without blocking. */
export const SAFETY_KEYWORDS = [
  "airbag",
  "brake failure",
  "brakes failed",
  "brakes not working",
  "can't stop",
  "cannot stop",
  "collision",
  "crash",
  "explosion",
  "fire",
  "flames",
  "fuel leak",
  "gas leak",
  "no brakes",
  "on fire",
  "overheating",
  "pull over",
  "seized",
  "smoke",
  "sparks",
  "stalling",
  "steering failure",
  "steering locked",
  "steering wheel",
  "stuck accelerator",
  "uncontrollable",
  "won't stop",
] as const;
